import test from 'node:test';
import type {TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createAuthService} from '../src/auth-core.ts';
import type {AdminAccountRequest,AdminAccountDelivery} from '../src/admin-account-operations.ts';
const password='synthetic account original password';
async function setup(t:TestContext){const root=await mkdtemp(join(tmpdir(),'admin-account-'));let now=1800000000000;const options={database:join(root,'auth.sqlite'),encryptionKey:randomBytes(32),roles:{member:['site.read'],editor:['site.read','site.write'],support:['site.read','auth.users.read','auth.users.manage'],admin:['*']},defaultRole:'member',now:()=>now};const service=await createAuthService(options);t.after(async()=>{await service.close();await rm(root,{recursive:true,force:true});});const admin=await service.bootstrapAdmin({email:'owner@example.test',password}),first=await service.register({email:'first@example.test',password}),second=await service.register({email:'second@example.test',password});return {service,admin,first,second,options,advance:(value:number)=>{now+=value;}};}
const token=(messages:AdminAccountDelivery[],purpose:string)=>messages.find(message=>message.kind==='token'&&message.purpose===purpose) as Extract<AdminAccountDelivery,{kind:'token'}>;
test('verification and forced-password-reset tokens remain inert until delivery commit',async t=>{
 const {service,admin,first}=await setup(t);const base={actorToken:admin.token,accountIds:[first.user.id],reason:'Reviewed support request'};
 const verification=await service.stageAccountAdministration({...base,action:'resend-verification'});assert.equal((await service.getUser(first.user.id))?.emailVerified,false);await assert.rejects(service.consumeVerification(token(verification.deliveries,'verify-email').token));await service.completeAccountAdministration({actorToken:admin.token,operationId:verification.operationId});await service.consumeVerification(token(verification.deliveries,'verify-email').token);assert.equal((await service.getUser(first.user.id))?.emailVerified,true);
 const reset=await service.stageAccountAdministration({...base,action:'force-password-reset'}),raw=token(reset.deliveries,'reset-password').token;await assert.rejects(service.resetPassword({token:raw,password:'synthetic replacement password'}));await service.completeAccountAdministration({actorToken:admin.token,operationId:reset.operationId});assert.equal(await service.authenticate(first.token),null);await assert.rejects(service.login({email:first.user.email,password}));await service.resetPassword({token:raw,password:'synthetic replacement password'});assert.ok(await service.login({email:first.user.email,password:'synthetic replacement password'}));await assert.rejects(service.completeAccountAdministration({actorToken:admin.token,operationId:reset.operationId}));
});
test('bulk role assignment is bounded and atomic across current delegation and target versions',async t=>{
 const {service,admin,first,second}=await setup(t);const base={actorToken:admin.token,reason:'Reviewed batch',action:'assign-roles' as const,roles:['editor']};
 await assert.rejects(service.stageAccountAdministration({...base,accountIds:[first.user.id,admin.user.id]}),{code:'self_administration_denied'});assert.deepEqual((await service.getUser(first.user.id))?.roles,['member']);await assert.rejects(service.stageAccountAdministration({...base,accountIds:Array.from({length:51},(_,i)=>String(i))}),{code:'invalid_administration'});
 const stale=await service.stageAccountAdministration({...base,accountIds:[first.user.id,second.user.id]});await service.updateProfile({token:second.token,profile:{displayName:'Changed'}});await assert.rejects(service.completeAccountAdministration({actorToken:admin.token,operationId:stale.operationId}),{code:'account_changed'});assert.deepEqual((await service.getUser(first.user.id))?.roles,['member']);
 const ready=await service.stageAccountAdministration({...base,accountIds:[first.user.id,second.user.id]});assert.equal(ready.deliveries.length,2);assert.deepEqual(await service.completeAccountAdministration({actorToken:admin.token,operationId:ready.operationId}),{affected:2});assert.deepEqual((await service.getUser(first.user.id))?.roles,['editor']);assert.equal(await service.authenticate(first.token),null);assert.equal(await service.authenticate(second.token),null);
});
test('admin deletion honors grace, user cancellation and admin cancellation with revocation',async t=>{
 const {service,admin,first}=await setup(t),base={actorToken:admin.token,accountIds:[first.user.id],reason:'Reviewed deletion request'};
 let staged=await service.stageAccountAdministration({...base,action:'schedule-deletion'});assert.equal((await service.getUser(first.user.id))?.status,'active');await service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId});assert.equal((await service.getUser(first.user.id))?.status,'pending-delete');assert.equal(await service.authenticate(first.token),null);await service.cancelDeletion(token(staged.deliveries,'cancel-deletion').token);assert.equal((await service.getUser(first.user.id))?.status,'active');
 staged=await service.stageAccountAdministration({...base,action:'schedule-deletion'});await service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId});const cancellation=await service.stageAccountAdministration({...base,action:'cancel-deletion'});await service.completeAccountAdministration({actorToken:admin.token,operationId:cancellation.operationId});assert.equal((await service.getUser(first.user.id))?.status,'active');await assert.rejects(service.cancelDeletion(token(staged.deliveries,'cancel-deletion').token));
});
test('administrative requested email changes retain 24-hour verification and old-address cancellation',async t=>{
 const {service,admin,first,advance}=await setup(t),base={actorToken:admin.token,accountIds:[first.user.id],reason:'Reviewed email change',action:'request-email-change' as const,email:'new@example.test'};
 let staged=await service.stageAccountAdministration(base);assert.equal(staged.deliveries[0]?.kind,'token');assert.equal(token(staged.deliveries,'cancel-email-change').email,first.user.email);await service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId});await assert.rejects(service.confirmEmailChange(token(staged.deliveries,'verify-email-change').token),{code:'email_change_cooldown'});await service.cancelEmailChange(token(staged.deliveries,'cancel-email-change').token);
 staged=await service.stageAccountAdministration(base);await service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId});advance(86400000);await service.confirmEmailChange(token(staged.deliveries,'verify-email-change').token);assert.equal((await service.getUser(first.user.id))?.email,'new@example.test');assert.equal(await service.authenticate(first.token),null);
});
test('audited method inspection excludes secrets and removal preserves a primary sign-in method',async t=>{
 const {service,admin,first,advance}=await setup(t);await service.linkExternal({actorToken:first.token,provider:'example',subject:'private-subject'});await service.addPasskey({actorToken:first.token,credential:{id:'c'.repeat(24),publicKey:Buffer.from('private-public-key-material').toString('base64url'),counter:0}});
 const methods=await service.inspectAccountAuthentication({actorToken:admin.token,accountId:first.user.id,reason:'Reviewed sign-in methods'});assert.equal(methods.external[0]?.provider,'example');assert.equal(methods.external[0]?.added,1800000000000);assert.equal(methods.passkeys[0]?.added,1800000000000);assert.equal(methods.passkeys[0]?.lastUsed,undefined);advance(1000);const key=(await service.getPasskey('c'.repeat(24)))!;await service.issueSession(first.user.id,{method:'passkey',proof:{...key.proof,newCounter:1}});const used=await service.inspectAccountAuthentication({actorToken:admin.token,accountId:first.user.id,reason:'Review method activity'});assert.equal(used.passkeys[0]?.lastUsed,1800000001000);assert.doesNotMatch(JSON.stringify(methods),/private-subject|private-public-key|publicKey|passwordHash/);
 const stage=await service.stageAccountAdministration({actorToken:admin.token,accountIds:[first.user.id],reason:'Requested method removal',action:'remove-external',externalId:methods.external[0]!.id});await service.completeAccountAdministration({actorToken:admin.token,operationId:stage.operationId});assert.equal(await service.findExternal('example','private-subject'),null);assert.equal(await service.authenticate(first.token),null);
 const externalOnly=await service.createExternalAccount({email:'external@example.test',provider:'example',subject:'only',emailVerified:true});const only=await service.inspectAccountAuthentication({actorToken:admin.token,accountId:externalOnly.id,reason:'Inspect only method'});await assert.rejects(service.stageAccountAdministration({actorToken:admin.token,accountIds:[externalOnly.id],reason:'Would remove last method',action:'remove-external',externalId:only.external[0]!.id}),{code:'last_sign_in_method'});
});
test('stage cancellation, actor changes and configuration migration prevent delayed account mutations',async t=>{
 const {service,admin,first,options}=await setup(t),request:AdminAccountRequest={actorToken:admin.token,accountIds:[first.user.id],reason:'Reviewed manual verification',action:'verify-email'};
 let staged=await service.stageAccountAdministration(request);await service.cancelAccountAdministration({actorToken:admin.token,operationId:staged.operationId});await assert.rejects(service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId}));assert.equal((await service.getUser(first.user.id))?.emailVerified,false);
 staged=await service.stageAccountAdministration(request);await service.updateProfile({token:admin.token,profile:{displayName:'Updated administrator'}});await assert.rejects(service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId}),{code:'administration_actor_changed'});
 staged=await service.stageAccountAdministration(request);const revision=await service.getConfigurationRevision(),migrated=await createAuthService({...options,configurationTag:'New reviewed policy',approveConfigurationChangeFrom:revision});t.after(()=>migrated.close());const login=await migrated.login({email:admin.user.email,password});await assert.rejects(migrated.completeAccountAdministration({actorToken:login.token,operationId:staged.operationId}),{code:'administration_unavailable'});assert.equal((await migrated.getUser(first.user.id))?.emailVerified,false);
});
test('current permission ceilings, fresh authentication and stage expiry fail closed',async t=>{
 const {service,admin,first,second,advance}=await setup(t);await service.adminSetRoles({actorToken:admin.token,accountId:second.user.id,roles:['support'],reason:'Scoped support authority'});const support=await service.login({email:second.user.email,password});await assert.rejects(service.stageAccountAdministration({actorToken:support.token,accountIds:[first.user.id],action:'assign-roles',roles:['admin'],reason:'Forbidden privilege assignment'}),{code:'delegation_ceiling_exceeded'});await assert.rejects(service.inspectAccountAuthentication({actorToken:support.token,accountId:admin.user.id,reason:'Privileged target'}),{code:'delegation_ceiling_exceeded'});
 const staged=await service.stageAccountAdministration({actorToken:admin.token,accountIds:[first.user.id],action:'verify-email',reason:'Delayed verification'});advance(300001);await assert.rejects(service.completeAccountAdministration({actorToken:admin.token,operationId:staged.operationId}),{code:'fresh_authentication_required'});const refreshed=await service.login({email:admin.user.email,password});await assert.rejects(service.completeAccountAdministration({actorToken:refreshed.token,operationId:staged.operationId}),{code:'administration_unavailable'});assert.equal((await service.getUser(first.user.id))?.emailVerified,false);
});
