import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { createAuthService } from '../src/auth-core.ts';
test('service applies full user filters, private stable cursors and audited identifier reveal',async t=>{
    const root=await mkdtemp(join(tmpdir(),'urlcode-query-service-'));t.after(()=>rm(root,{recursive:true,force:true}));
    let now=1700000000000;
    const service=await createAuthService({database:join(root,'auth.sqlite'),encryptionKey:randomBytes(32),roles:{member:[],admin:['*'],support:['auth.users.read']},defaultRole:'member',now:()=>now});t.after(()=>service.close());
    const admin=await service.bootstrapAdmin({email:'operator@example.test',password:'correct horse battery staple'});
    const first=await service.register({email:'first@example.test',password:'correct horse battery staple',profile:{displayName:'Same',locale:'fr'},device:{id:'a'.repeat(43),label:'Test device'}});
    now+=1000;
    const second=await service.register({email:'second@example.test',password:'correct horse battery staple',profile:{displayName:'Same',locale:'en'}});
    const devices=await service.listAllSessions({accountId:first.user.id,device:'Test device',createdFrom:now-1000,createdTo:now-1});
    assert.equal(devices.sessions.length,1);assert.equal(devices.sessions[0]?.accountId,first.user.id);
    assert.equal((await service.listAllSessions({device:'missing device'})).sessions.length,0);
    await assert.rejects(service.listAllSessions({createdFrom:now,createdTo:now-1}));
    const filtered=await service.listUsers({query:'Same',locale:'fr',method:'password',verified:false,createdTo:now-1});
    assert.equal(filtered.users.length,1);assert.equal(filtered.users[0]!.id,first.user.id);assert.equal(filtered.users[0]!.observedLastSeen,now-1000);
    const page=await service.listUsers({query:'Same',sort:'email',limit:1});assert.ok(page.next);
    assert.ok(!Buffer.from(page.next!,'base64url').toString().includes('@'));
    const next=await service.listUsers({query:'Same',sort:'email',limit:1,after:page.next});assert.equal(next.users[0]!.id,second.user.id);assert.equal(next.next,undefined);
    await assert.rejects(service.listUsers({sort:'created',after:page.next}));
    await service.adminSetRoles({actorToken:admin.token,accountId:second.user.id,roles:['support'],reason:'Create support fixture'});
    const support=await service.login({email:'second@example.test',password:'correct horse battery staple'});
    await assert.rejects(service.adminAddNote({actorToken:support.token,accountId:first.user.id,reason:'Not authorized'}),/permission/);
    await service.adminAddNote({actorToken:admin.token,accountId:first.user.id,reason:'Verified support case context'});
    assert.equal((await service.listAudit({subject:first.user.id,action:'admin.note'})).events[0]?.reason,'Verified support case context');
    await assert.rejects(service.adminReveal({actorToken:support.token,accountId:first.user.id,reason:'Investigate account'}),/permission/);
    assert.deepEqual(await service.adminReveal({actorToken:admin.token,accountId:first.user.id,reason:'Requested support verification'}),{id:first.user.id,email:'first@example.test'});
    const audit=await service.listAudit({action:'admin.identifier_revealed',subject:first.user.id});assert.equal(audit.events.length,1);assert.equal(audit.events[0]!.actor,admin.user.id);assert.equal(audit.events[0]!.reason,'Requested support verification');
    now+=300001;
    await assert.rejects(service.adminReveal({actorToken:admin.token,accountId:first.user.id,reason:'Expired confirmation'}),/fresh/);
});
