import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, stat, readFile, writeFile, symlink } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { createBackup, restoreBackup } from '../src/backup.ts';
import { createAuthService } from '../src/auth-core.ts';
test('online WAL backup restores an isolated account with separate matching keys and config', async (t) => {
    const root = await mkdtemp(join(tmpdir(), 'urlcode-backup-'));
    t.after(() => rm(root, { recursive: true, force: true }));
    const projectRoot = join(root, 'project');
    await mkdir(projectRoot, { mode: 0o700 });
    const database = join(root, 'live.sqlite'), destination = join(root, 'backup.sqlite'), restored = join(root, 'restored.sqlite'), key = Buffer.alloc(32, 9), options = { database, encryptionKey: key, roles: { user: [], admin: ['*'] }, defaultRole: 'user' };
    const service = await createAuthService(options);
    t.after(() => service.close());
    const user = await service.register({ email: 'backup@example.test', password: 'synthetic backup password' });
    const info = await createBackup({ database, destination, projectRoot });
    assert.equal(info.format, 'urlcode-auth-sqlite-v1');
    assert.ok(info.bytes > 0);
    assert.equal((await stat(destination)).mode & 0o777, 0o600);
    assert.equal((await readFile(destination)).includes(key), false);
    await restoreBackup({ backup: destination, destination: restored, projectRoot });
    const recovered = await createAuthService({ ...options, database: restored });
    t.after(() => recovered.close());
    assert.equal((await recovered.login({ email: user.user.email, password: 'synthetic backup password' })).user.id, user.user.id);
    await assert.rejects(createBackup({ database, destination, projectRoot }), /already exists/);
    await assert.rejects(restoreBackup({ backup: destination, destination: database, projectRoot }), /already exists/);
});
test('backup refuses aliases, public files, project outputs and invalid or executable schemas', async (t) => {
    const root = await mkdtemp(join(tmpdir(), 'urlcode-backup-bad-'));
    t.after(() => rm(root, { recursive: true, force: true }));
    const projectRoot = join(root, 'project');
    await mkdir(projectRoot, { mode: 0o700 });
    const database = join(root, 'bad.sqlite'), destination = join(root, 'copy.sqlite');
    await writeFile(database, 'not sqlite', { mode: 0o600 });
    await assert.rejects(createBackup({ database, destination, projectRoot }));
    await assert.rejects(stat(destination), { code: 'ENOENT' });
    await symlink(database, join(root, 'alias.sqlite'));
    await assert.rejects(createBackup({ database: join(root, 'alias.sqlite'), destination, projectRoot }), /private regular/);
    await assert.rejects(createBackup({ database, destination: join(projectRoot, 'copy.sqlite'), projectRoot }), /outside/);
    await rm(database);
    const db = new DatabaseSync(database);
    db.exec('PRAGMA application_id=1430345032; PRAGMA user_version=1; CREATE TABLE auth_test(id INTEGER); CREATE VIEW auth_bad AS SELECT * FROM auth_test;');
    db.close();
    const { chmod } = await import('node:fs/promises');
    await chmod(database, 0o600);
    await assert.rejects(createBackup({ database, destination, projectRoot }), /validation/);
    await assert.rejects(stat(destination), { code: 'ENOENT' });
});
