import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';
const cli = fileURLToPath(new URL('../src/cli.ts', import.meta.url));
test('operator CLI bootstraps without exposing session/password and supports backup and inspection', async (t) => {
    const root = await mkdtemp(join(tmpdir(), 'urlcode-auth-cli-'));
    t.after(() => rm(root, { recursive: true, force: true }));
    await mkdir(join(root, 'app'));
    const operator = join(root, 'operator.mjs'), database = join(root, 'accounts.sqlite');
    await writeFile(operator, `import {createAuthService} from ${JSON.stringify(new URL('../src/auth-core.ts', import.meta.url).href)}; export default await createAuthService({database:${JSON.stringify(database)},encryptionKey:new Uint8Array(32).fill(7),roles:{member:[],admin:['*']},defaultRole:'member',registrationMode:'off'});`);
    const run = (command: string, input?: unknown) => spawnSync(process.execPath, [cli, command, '--operator-file', operator], { input: input === undefined ? undefined : JSON.stringify(input), encoding: 'utf8', timeout: 20000 });
    const password = 'synthetic-bootstrap-passphrase', created = run('bootstrap', { email: 'admin@example.com', password });
    assert.equal(created.status, 0, created.stderr);
    assert.ok(!created.stdout.includes(password));
    assert.ok(!created.stdout.includes('"token"'));
    const user = JSON.parse(created.stdout) as {
        id: string;
    };
    assert.equal(run('bootstrap', { email: 'second@example.com', password }).status, 1);
    const configuration = run('configuration');
    assert.equal(configuration.status, 0, configuration.stderr);
    assert.match(JSON.parse(configuration.stdout).revision, /^[a-f0-9]{64}$/);
    const validated = run('validate');
    assert.equal(validated.status, 0, validated.stderr);
    assert.equal(JSON.parse(validated.stdout).revision, JSON.parse(configuration.stdout).revision);
    assert.equal(JSON.parse(validated.stdout).liveProviders, 'unverified');
    assert.ok(!validated.stdout.includes(password));
    assert.ok(!validated.stdout.includes(database));
    const doctor = run('doctor');
    assert.equal(doctor.status, 0, doctor.stderr);
    assert.equal(JSON.parse(doctor.stdout).accounts, 1);
    const sessions = run('sessions', { accountId: user.id });
    assert.equal(sessions.status, 0, sessions.stderr);
    assert.ok(!sessions.stdout.includes('"hash"'));
    assert.equal(run('revoke', { accountId: user.id }).status, 0);
    const cleanup = run('cleanup');
    assert.equal(cleanup.status, 0, cleanup.stderr);
    assert.ok(JSON.parse(cleanup.stdout));
    const backup = spawnSync(process.execPath, [cli, 'backup'], { input: JSON.stringify({ database, destination: join(root, 'snapshot.sqlite'), projectRoot: join(root, 'app') }), encoding: 'utf8', timeout: 20000 });
    assert.equal(backup.status, 0, backup.stderr);
    const failure = spawnSync(process.execPath, [cli, 'bootstrap', '--operator-file', 'SECRET-relative.mjs'], { encoding: 'utf8', timeout: 10000 });
    assert.equal(failure.status, 1);
    assert.ok(!failure.stderr.includes('SECRET'));
    // A path-only interface never expands shell syntax or invokes a shell.
    assert.ok(pathToFileURL(operator).protocol === 'file:');
});
