export const englishEmailCatalogue = Object.freeze({
    'admin-verify-email': { subject: 'Account administration requested', text: 'An administrator requested to verify your account email. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-force-password-reset': { subject: 'Account administration requested', text: 'An administrator requested to require a new account password. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-schedule-deletion': { subject: 'Account administration requested', text: 'An administrator requested to schedule account deletion. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-cancel-deletion': { subject: 'Account administration requested', text: 'An administrator requested to cancel account deletion. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-remove-passkey': { subject: 'Account administration requested', text: 'An administrator requested to remove an account passkey. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-remove-external': { subject: 'Account administration requested', text: 'An administrator requested to remove an external sign-in method. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-request-email-change': { subject: 'Account administration requested', text: 'An administrator requested to change your account email. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-assign-roles': { subject: 'Account administration requested', text: 'An administrator requested to change your account role assignments. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },
    'admin-resend-verification': { subject: 'Account administration requested', text: 'An administrator requested to send account email verification. This notice does not confirm completion.\n\nReview your account at {link}. If you did not expect this, contact the account operator.' },

    'verify-email': { subject: 'Verify your email address', text: 'Verify your email address by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.' },
    'reset-password': { subject: 'Reset your password', text: 'Reset your password by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.' },
    'cancel-deletion': { subject: 'Cancel account deletion', text: 'Cancel account deletion by opening this link:\n\n{link}\n\nAccount deletion was requested. If you did not request this, use this link to cancel the deletion before the grace period ends. Never share this link.' },
    invitation: { subject: 'Create your invited account', text: 'Create your invited account by opening this link:\n\n{link}\n\nIf you did not request this, ignore this email. Never share this link.' },
    'verify-email-change': { subject: 'Verify your new email address', text: 'Verify your new email address by opening this link:\n\n{link}\n\nVerification confirms the new address. The change only activates after the 24-hour cooldown. Never share this link.' },
    'cancel-email-change': { subject: 'Cancel an email address change', text: 'Cancel an email address change by opening this link:\n\n{link}\n\nA change to your account email was requested. Use this cancellation link before completion if this was not you. Never share this link.' },
    'sign-in-code': { subject: 'Your sign-in code', text: 'Your sign-in code is: {code}\n\nEnter it at {link}\n\nIf you did not request this, ignore this email. Never share this code.' },
    'signup-code': { subject: 'Verify your email address', text: 'Your signup code is: {code}\n\nEnter it in the browser where you started signing up at {link}\n\nIf you did not request this, ignore this email. Never share this code.' },
    'factor-recovery': { subject: 'Second-factor recovery requested', text: 'Someone requested recovery of your account second factor. Confirm in the browser where you started recovery:\n\n{link}\n\nConfirmation starts a 24-hour waiting period. After that period, return to the confirmation link to finish recovery and enroll a new second factor. Existing sessions will be revoked when recovery completes.\n\nIf this was not you, cancel the request before it completes:\n\n{cancelLink}\n\nNever share these links.' },
    'manual-recovery-warning': { subject: 'Manual account recovery approved', text: 'Two administrators approved a manual recovery request for your account. Completing recovery will replace your sign-in methods and revoke existing sessions. If you did not request this, contact the account operator immediately.' },
    'manual-recovery': { subject: 'Restore account access', text: 'Two administrators approved your account recovery. Choose a new password and enroll a second factor at:\n\n{link}\n\nThis link expires in 30 minutes. Your existing sign-in methods and sessions will be revoked when recovery completes. Never share this link.' },
    'new-device': { subject: 'Account security notification', text: 'A new device signed in to your account.\n\nReview your account at {link}. If this was not you, contact the account operator.' },
    'password-changed': { subject: 'Account security notification', text: 'Your account password changed.\n\nReview your account at {link}. If this was not you, contact the account operator.' },
    'email-changed': { subject: 'Account security notification', text: 'Your account email address changed.\n\nReview your account at {link}. If this was not you, contact the account operator.' },
    'registration-attempt': { subject: 'Account security notification', text: 'Someone tried to create an account with your email address. Your existing account was not changed.\n\nReview your account at {link}. If this was not you, contact the account operator.' },
});
for (const template of Object.values(englishEmailCatalogue)) Object.freeze(template);
export type EmailTemplateKey = keyof typeof englishEmailCatalogue;
export interface EmailCopyOptions { defaultLocale?: string; catalogues?: Record<string, Partial<Record<EmailTemplateKey, { subject: string; text: string }>>>; }
export interface EmailCopy { render(key: EmailTemplateKey, values: Readonly<Record<string,string>>, locale?: string): { subject: string; text: string }; }
const slots=(text:string)=>[...new Set([...text.matchAll(/\{([A-Za-z]+)\}/g)].map(match=>match[1]!))].sort();
function canonical(value:string):string { if(typeof value!=='string'||value.length>64)throw new Error('Invalid email locale'); return Intl.getCanonicalLocales(value)[0]!; }
/** Plain-text notices only. Translations must preserve every required capability placeholder. */
export function createEmailCopy(options:EmailCopyOptions={}):EmailCopy {
    const defaultLocale=canonical(options.defaultLocale??'en'), catalogues=new Map<string,Partial<Record<EmailTemplateKey,{subject:string;text:string}>>>();
    const entries=Object.entries(options.catalogues??{}); if(entries.length>32)throw new Error('Too many email locales');
    for(const [raw,source] of entries){const locale=canonical(raw);if(catalogues.has(locale)||!source||typeof source!=='object'||Array.isArray(source))throw new Error('Invalid email catalogue');const copy:Partial<Record<EmailTemplateKey,{subject:string;text:string}>>={};let total=0;
        for(const [key,value] of Object.entries(source)){if(!Object.hasOwn(englishEmailCatalogue,key)||!value||typeof value.subject!=='string'||typeof value.text!=='string'||!value.subject||value.subject.length>160||/[\r\n\x00-\x1f\x7f]/.test(value.subject)||value.text.length>16384||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value.text)||slots(value.subject).length||JSON.stringify(slots(value.text))!==JSON.stringify(slots(englishEmailCatalogue[key as EmailTemplateKey].text)))throw new Error('Invalid email template');total+=value.subject.length+value.text.length;if(total>65536)throw new Error('Email catalogue too large');copy[key as EmailTemplateKey]=Object.freeze({subject:value.subject,text:value.text});}
        catalogues.set(locale,Object.freeze(copy));
    }
    return Object.freeze({render(key:EmailTemplateKey,values:Readonly<Record<string,string>>,locale?:string){if(!Object.hasOwn(englishEmailCatalogue,key))throw new Error('Unknown email template');const language=canonical(locale??defaultLocale),template=catalogues.get(language)?.[key]??catalogues.get(language.split('-')[0]!)?.[key]??catalogues.get(defaultLocale)?.[key]??englishEmailCatalogue[key];const text=template.text.replace(/\{([A-Za-z]+)\}/g,(_match,name:string)=>{const value=values[name];if(typeof value!=='string'||value.length>4096)throw new Error('Missing email value');return value;});if(text.length>16384)throw new Error('Rendered email too large');return {subject:template.subject,text};}});
}
