export { createAuthService, AuthError } from './auth-core.ts';
export type { AuthService, AuthPrincipal, AuthUser } from './auth-core.ts';
export { authExtension, hasPermission } from './auth.ts';
export type { AuthExtensionOptions } from './auth.ts';
export type { AuthHttpOptions, AuthHttpResponse } from './auth-ui.ts';
export { AuthHttp, AuthHttpError, csrfField, escapeHtml, formField, httpFailure, jsonResponse, pageResponse, readFields, screenResponse, wantsJson } from './auth-ui.ts';
export type { Screen, ScreenOptions, UiHost } from './auth-ui.ts';
export { authTemplates, authTemplateNames, authUiTemplates } from './auth-templates.ts';
export type { AuthTemplate } from './auth-templates.ts';
export { createOidcProvider } from './oidc.ts';
export type { OidcProvider, OidcFlow, OidcIdentity, OidcProviderOptions } from './oidc.ts';
export { createPasskeyProvider } from './passkeys.ts';
export type { PasskeyProvider, StoredPasskey, PasskeyProviderOptions } from './passkeys.ts';
export { createSesSender, createDevelopmentSender } from './senders.ts';
export { createPresentation, englishCatalogue, englishCatalogue as authCatalogue } from './presentation.ts';
export type { Presentation, PresentationOptions, PresentationContext, Catalogue, ThemeVariables } from './presentation.ts';
export * from './registration.ts';
export { createGoogleProvider, createAppleProvider } from './providers.ts';
export type { GoogleProviderOptions, AppleProviderOptions } from './providers.ts';
export { createBackup, restoreBackup } from './backup.ts';
export type { BackupOptions, BackupResult, RestoreOptions } from './backup.ts';
export type { AuthOptions, AuthSessionResult, AuthSession, AuthAuditEvent, AuthCase } from './auth-core.ts';
export { initAuthentication, scaffold } from './scaffold.ts';
export type { AuthenticationScaffold, ScaffoldRequest, ScaffoldResult, ScaffoldFile } from './scaffold.ts';
export type { EmailSender, TokenSender, TokenMessage, EmailCodeMessage, FactorRecoveryMessage, SignupCodeMessage, SecurityNotice, SesSenderOptions, DevelopmentSenderOptions } from './senders.ts';
export { createPasswordBreachChecker } from './password-policy.ts';
export type { PasswordBreachOptions } from './password-policy.ts';
export type { AuthDailyMetric, AuthHookStats, AuthLifecycleEvent, AuthCredentials, AuthSecondFactor, AuthDevice, AuthPasskey, AuthProof, ExternalAuthProof, PasskeyAuthProof, SignupBinding, SignupState, SignupStart } from './auth-core.ts';
export { createAuthPreset } from './presets.ts';
export type { AuthPreset, AuthPresetOptions } from './presets.ts';
export type { AuthRestriction, AuthSecurityPolicy } from './auth-core.ts';
export { verifyDeployment } from './deployment-check.ts';
export type { DeploymentCheckOptions, DeploymentCheckResult } from './deployment-check.ts';
export type { ManualRecoveryService, ManualRecoveryCase, ManualRecoveryDelivery, ManualRecoveryEvidence } from './manual-recovery.ts';
export type { UserQuery, ValidatedUserQuery } from './user-query.ts';
export { validateUserQuery } from './user-query.ts';
export { createEmailCopy, englishEmailCatalogue } from './email-copy.ts';
export type { EmailCopy, EmailCopyOptions, EmailTemplateKey } from './email-copy.ts';
export type { AdminAccountAction, AdminAccountDelivery, AdminAccountRequest, AdminAuthenticationMethods, AdminAccountService } from './admin-account-operations.ts';
export type { TurnstileWidget } from './challenge-ui.ts';
export { createTurnstileChallenge } from './challenge.ts';
export type { AuthChallenge, AuthChallengeInput, TurnstileChallengeOptions } from './challenge.ts';
